### PR TITLE
Add legal country for set and not-set membership proofs

### PR DESCRIPTION
**Pull request by DOBEN**
## Purpose

The browser wallet calls the `verifySetStatement` function to exclude all the attributes not allowed for these types of proofs. The `LegalCountry` attribute (from company IDs) has been added recently. Propagating this addition to the SDK.

Related: https://github.com/Concordium/concordium-browser-wallet/issues/484
Related: https://github.com/Concordium/concordium-base/pull/542

## Changes

- Add legal country for set and not-set membership proofs

### CODE REVIEW

**Review by soerenbf — APPROVED** [review]

**Comment by nhs-it** [comment]
It seems all checks passed? When will the chrome ext be released for testnet?

**Comment by DOBEN** [comment]
Dear @nhs-it, 
the `web-sdk` version 8.1.0 has been released now with the above changes:
https://www.npmjs.com/package/@concordium/web-sdk

We are working on the browser wallet release that includes `web-sdk` version 8.1.0.

**Comment by nhs-it** [comment]
Dear @DOBEN - any update on the browser wallet using web-sdk 8.1.0 - on testnet?

**Comment by DOBEN** [comment]
@nhs-it 
We are testing and preparing the browser wallet release at the moment.
https://github.com/Concordium/concordium-browser-wallet/pull/526

**Comment by DOBEN** [comment]
@nhs-it The new browser wallet Version 1.7.1. This wallet include company ZK proofs now since the web-sdk has been updated.

https://developer.concordium.software/en/mainnet/net/release-notes/release-notes-lp.html#bw

**Comment by nhs-it** [comment]
Great! thank you

**Pull request merged**
